version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      - MYSQL_DATABASE=BankDB
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    networks:
      - my-network

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/BankDB
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8080

    networks:
      - my-network

  angular-app:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: angular_container
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - my-network

volumes:
  mysql_data:

networks:
  my-network:
    driver: bridge
